version: 0.0
os: linux
files:
  - source: /
    destination: /your/app/directory
hooks:
  BeforeInstall:
    - location: scripts/update_nginx_log_level.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
